a = input('Escreva algo: ')

print(type(a))
print(('alfanumérico '), a.isalnum())
print(('ascii'), a.isascii())
print(('decimal'), a.isdecimal())
print(('digito'), a.isdigit())
print(('identificador'), a.isidentifier())
print(('minúscula'), a.islower())
print(('imprimível'), a.isprintable())
print(('espaço'), a.isspace())
print(('título'), a.istitle())
print(('maiuscula'), a.isupper())
